### ISSUE TITLE
vendor/bundleを.gitignoreに設定しよう

### ISSUE THREAD

**Issue by Kta-M** [TsuMakoto/blog-system#1]
gemをインストールする`vendor/bundle`ディレクトリは、通常githubに上げません。
それぞれが各環境でインストールします。

単純に管理するデータが多くなってしまうのもあるし、
gemの中にはCをコンパイルするものもあって、環境によって違うバイナリがができるので各環境で共通して使えないってのもある。

**Comment by Kta-M** [comment]
単純に.gitignoreを設定しても、すでに上がっているファイルは消えないのでご注意を。

**Comment by TsuMakoto** [comment]
修正しました
https://github.com/TsuMakoto/blog-system/commit/38d095f361e07affcc37cd026656db838cd80023

**Comment by Kta-M** [comment]
👍
