### ISSUE TITLE
未ログインのユーザーの処理はdeviseの機能を使えば簡単にできる

### ISSUE THREAD

**Issue by ippachi** [TsuMakoto/blog-system#3]
deviseの機能を調べてみて

**Comment by TsuMakoto** [comment]
Thanks！
https://github.com/TsuMakoto/blog-system/commit/0002726db4ff958d8d8808aaed9a48c6382041dd

**Comment by ippachi** [comment]
`current_user.nil?` を使ってるところも適用できないかね？

**Comment by ippachi** [comment]
もうひとつ！
postやupdateやdestroy系のコントローラーメソッドにログインチェックが不要かどうか考えてみて！

**Comment by TsuMakoto** [comment]
了解！
とりあえずhttps://github.com/TsuMakoto/blog-system/issues/3#issuecomment-492087365 に対して＞ https://github.com/TsuMakoto/blog-system/commit/eca2387fab6f90227b973d00c8ebfa3684cc3823

**Comment by TsuMakoto** [comment]
https://github.com/TsuMakoto/blog-system/issues/3#issuecomment-492089243
外部からjson送ってデータ改ざんされる可能性あるから認証はすべきっていうことでOK？
https://github.com/TsuMakoto/blog-system/commit/07efeb39efa29ed99ebb30ed862d659e57531ff4

**Comment by ippachi** [comment]
OK!
認証系はまず全部かけること前提で、認証があると困るところだけ外していくと過不足なくかけやすいと思う！
@TsuMakoto
