### ISSUE TITLE
railsでurlやpathを扱う時はできるだけ文字列ではなくメソッドを使おう

### ISSUE THREAD

**Issue by ippachi** [TsuMakoto/blog-system#4]
`routes.rb` の `as` だったり `resources` などでメソッドが生成されるのでそっちを使おう

変更があったときに置換がやりやすくなるし、タイポがエラーになるので気づきやすい

**Comment by TsuMakoto** [comment]
全てメソッドで置き換えました
https://github.com/TsuMakoto/blog-system/commit/b6199bd8abb5bc566337f9cbb16a65d6c93c64f6
多いので暇な時にお願い

**Comment by ippachi** [comment]
OK!
このissueとは関係ないけどrubyのdoc commentにはYARDっていうフォーマットがあるから書くならその形式がよさそう！

https://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md
