### ISSUE TITLE
viewでfindやwhereはできるだけ使わないようにしよう

### ISSUE THREAD

**Issue by ippachi** [TsuMakoto/blog-system#7]
viewは表示のためのレイヤーなので、DBに関することはモデルやコントローラーに任せて、データだけ受け取って表示するようにしよう

**Comment by TsuMakoto** [comment]
アソシエーション使うところでついでに直ってました〜
↓これのhtml.erbファイルです
https://github.com/TsuMakoto/blog-system/commit/e0127cf16712c16e8d80ccbdb44985d66dfbd7cf

**Comment by ippachi** [comment]
👍
